mutation AddProductToCart($productId: UUID!, $quantity: Int!) @auth(level: USER) {
  cartItem_insert(data: {productId: $productId, userId_expr: "auth.uid", quantity: $quantity, createdAt_expr: "request.time"})
}

query GetProducts @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products {
    id
    name
    description
    price
    imageUrl
  }
}

query GetCartItems @auth(level: USER) {
  cartItems(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    product {
      id
      name
      description
      price
      imageUrl
    }
    quantity
  }
}

mutation PlaceOrder @auth(level: USER) {
  order_insert(data: {userId_expr: "auth.uid", orderDate_expr: "request.time", status: "pending", totalAmount: 0.0})
}