type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String!
  photoUrl: String
  shippingAddress: String
  billingAddress: String
}

type Product @table {
  name: String!
  price: Float!
  description: String!
  createdAt: Timestamp!
  imageUrl: String
  category: String
  stockQuantity: Int
}

type CartItem @table {
  user: User!
  product: Product!
  quantity: Int!
  createdAt: Timestamp!
}

type Order @table {
  user: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  priceAtPurchase: Float!
}